#####################################################################
#
#  This makefile builds the Watchpoint test program
#
#####################################################################

a.out:	test.c
	purify cc -g test.c

clean:
	/bin/rm -f a.out a.out*pure* test*pure* .pur*
